### ISSUE TITLE
UI: Range Slider

### ISSUE THREAD

**Issue by jenius** [jenius/axis#108]
It would be nice to have alternate styles for the range slider added to the UI section.

**Comment by dbox** [comment]
working on this

**Comment by dbox** [comment]
http://codepen.io/dbox/pen/MwKQqP

how's this?

**Comment by jenius** [comment]
Looks great! I'd just make the circular slider the default rather than the rectangular one, only because that's how the default slider UI looks. Thanks for the great work on this!
