### ISSUE TITLE
UI: Radio Buttons

### ISSUE THREAD

**Issue by jenius** [jenius/axis#109]
It would be nice to have alternate styles for radio buttons added to the UI section

**Comment by dbox** [comment]
Only a year and a half late. Hows this:

How's this?
http://codepen.io/dbox/pen/bdEgoQ/?editors=110

The mixin has to be called on the `label`.

Let me know what you think. I can easily do a pull request to add the mixin, but writing the test for this one might be hard for me.

**Comment by jenius** [comment]
Woah, this looks great! Love the ones on the left especially. Would love a pull request for those ones, if possible!

**Comment by dbox** [comment]
It's all the same mixin. Left would be default, then you can pass options
for the others. Shaded, etc.

I'll do a pr. Will let you know if I need help with tests.

**Comment by jenius** [comment]
Ah ok. Really no need for all that at the moment, we could just start with the simplest one. Axis doesn't aim to do full styling, just provide a quick simple base for you to build on and customize :grinning: 

That would also make it easier to test and implement!

**Comment by dbox** [comment]
So pass main selected color at least? Or nothing?

**Comment by jenius** [comment]
Yeah having color as an option sounds great!
