### ISSUE TITLE
Vertical Rhythm Needs to be Replaced

### ISSUE THREAD

**Issue by zspecza** [jenius/axis#114]
There is nothing quite wrong with the current implementation - it gets the job done, but I feel like it could be made a hell of a lot simpler because of features Stylus has that other pre-processors don't. The current implementation is ported from Compass and is thus built on the basis of features available in Sass, and every time you want to specify a new rhythm that is nested within another, you have to pass in the parent context:

``` stylus
.header
  padding-leader: 2, 18px
  // 18px is the font size of the parent element, not 16px - the default
```

There's also way too many mixins and functions to remember:

`adjust-font-size-to`
`leader`
`trailer`
`margin-leader`
`padding-leader`
`margin-trailer`
`padding-trailer`
`rhythm`
`leading-border`
`trailing-border`
`horizontal-borders`
`rhythm-borders`
`adjust-leading-to`
`-rhythm`

I've been pondering a new method that would be much simpler to use, and all it requires is one function: `rhythm()`. Since Stylus has awesome property bubbling (`@property`) for grabbing values, theoretically, there will be no need to pass in parent contexts.

`rhythm()` would check which property it is being used on, and simply "enclose" or wrap how you would set a value for that property as if you were setting it directly, so nothing is different other than that you're wrapping your values with `rhythm()`.

Hypothetically, the user would use it like this:

```
.thing
  font-size: rhythm(16px)
  padding: rhythm(24px, 0) // non-rhythm equivalent: padding: 24px, 0
```

Of course, it is simpler to specify a `base-font-size` and `base-line-height`, and then be able to specify any rhythm values as `1` leading, or `3` leading, so `rhythm()` should be able to normalize these values internally, so that they are interchangeable:

```
.thing
  font-size: rhythm(16px)
  padding: rhythm(1, 0)
```

Furthermore, I think that this re-implementation would be a perfect opportunity to incorporate [type-utils](https://github.com/blakeembrey/stylus-type-utils) into Axis, so that we can normalize between `rem` and `em` values:

```
rhythm-unit ?= 'rem'

.thing
  line-height: rhythm(1)
```

@jenius what do you think? This would take a lot of time but I have a feeling it'll be fun!

**Comment by thiagodebastos** [comment]
Heya, did we end up using a vertical-rhythm module after all?

**Comment by jenius** [comment]
Nope we removed vertical rhythm. There are a few other libraries if you
search github for "stylus vertical rhythm"
