### ISSUE TITLE
Axis Sass Port

### ISSUE THREAD

**Issue by nisaac2fly** [jenius/axis#122]
Hello, just finished watching your tutorial videos on roots and axis. Looking forward to start using these in my projects. 

Do you have any plans on porting axis this to Sass? 

> **AUTHOR EDIT:** A sass port is underway at the moment by a third party. Scroll to the bottom of this issue for discussion and a link to the project!

**Comment by dbox** [comment]
+1

**Comment by jenius** [comment]
A +1 here doesn't do any good here. The issue has been discussed and closed. If you are interested in a sass version and want to build and maintain it yourself, as stated previously I would be more than happy to help out though!

**Comment by dbox** [comment]
Haha. Not sure I even saw that it was closed. Just did a search for sass.

After running roots / stylus for last 3 projects We have to run straight sass on one now and I definitely miss axis. Maybe [*we*](https://github.com/kni-labs/rrssb) can help contribute or even take this on. /cc @ccampb13

How does it usually work with ports? Basically we'd be responsible for always making sure it's updated right?

**Comment by jenius** [comment]
Yeah basically. I would definitely be happy to work closely with you guys on it, and give heads up when any major changes come in etc, but I just don't have the bandwidth at the moment for the full build and long term maintenance by myself.

**Comment by dbox** [comment]
Okay we're officially working on this, slowly but surely. @ccampb13 is heading it up. Will let you know as we have more progress.

**Comment by jenius** [comment]
Whoo! That's awesome. Let me know if/where I can be of use :+1:

**Comment by dbox** [comment]
@ccampb13 has been plugging away, just starting with all the mixins. Still a bit more to go but you can see progress here:

https://github.com/kni-labs/axis-scss/tree/master/axis

We'll ping you when its mostly done. We'll probably need some help with some of the installation options, as well.

At some point it might be nice to re-open this issue, then if anyone wants to help they can.

**Comment by jenius** [comment]
Awesome, yeah definitely. I'll re-open it now and change the details so that it reads better for people looking for this. Once you guys have even a semi-stable port I'll add a note for it to the readme :grinning:

**Comment by dbox** [comment]
Still working on this. Basically got almost everything except the typography, which, I'm sure you know is the trickiest part. Will keep you posted.

**Comment by jenius** [comment]
:+1:

**Comment by dbox** [comment]
With the future post-css roadmap for Axis we can probably close this. We never [fully converted Axis to sass](https://github.com/kni-labs/axis-scss) but have created another slimmed down repo which has some of the basics: https://github.com/kni-labs/knapsack.
