### ISSUE TITLE
transition from Nib not coming through properly with native Nib disabled in DocPad

### ISSUE THREAD

**Issue by EnMod** [jenius/axis#169]
The underscore used in the following code to cache Nib's transition mixin is somehow carrying over into final output:

```stylus
//Cache nib transition mixin.
_transition = transition

transition()
  arguments = unquote('all .3s ease') unless arguments
  _transition: arguments
```

Is that because I disabled Nib for DocPad, meaning Axis would have nothing to cache with the declaration above the mixin?

**Comment by jenius** [comment]
Hi @EnMod! Sorry, I don't really understand what the issue is here. Is there any way you could try to dig a little deeper and isolate it to an issue with axis, specifically? I can't help with DocPad or Nib issues, really...

**Comment by EnMod** [comment]
Well to be specific, the issue is when just using transition() in my Stylus code, after having set my generator DocPad to prefer Axis over Nib, it doesn't process `_transition: arguments` as it should, producing `_transition: all .3s ease` instead of `transition: all .3s ease`.  On second though, this does look more like a problem with DocPad's Stylus plugin and my configuration.  Thanks for your input, I'll close this.
