### ISSUE TITLE
Feature: Ratio Box

### ISSUE THREAD

**Issue by abstracthat** [jenius/axis#170]
I think this is a useful mixin that is taken from the Scut scss library. It's used to set a specific width/height ratio for background images and video iframe embeds. Before I submit a PR I thought I gauge your interest.

```stylus
ratio-box(ratio = 1/1)
  ratio = remove-unit(ratio)
  overflow hidden
  position relative

  &:before
    content ''
    display block
    height 0
    padding-top (1 / ratio) * 100%

```

**Comment by jenius** [comment]
Yeah I use css code like this all the time. Definitely seems like a useful mixin that would have a place in axis.

**Comment by abstracthat** [comment]
I'm cleaning through my own library this week. I have a few other things that might make sense to add so I'll add each to an issue and once we determine which ones you want / where they should go then I'll add them all in one working session (as separate clean PR's of course) with the tests, etc.

**Comment by jenius** [comment]
Perfect :grinning:
