### ISSUE TITLE
Feature: Fluid Images

### ISSUE THREAD

**Issue by abstracthat** [jenius/axis#173]
I'm a little surprised this isn't in there as I have to add it to pretty much every project. Makes images, videos, and iframe embeds 100% width.

Could be added to `reset.styl` like `normalize-css()`.

```stylus
fluid-images()
  img,
  video,
  iframe
    max-width 100%
    height auto
    border 0
    -ms-interpolation-mode bicubic
    display block
```

**Comment by jenius** [comment]
Hmm, yeah I'd be ok with this

**Comment by abstracthat** [comment]
ok. I'll send the PR soon.
