### ISSUE TITLE
Feature: Border Box HTML

### ISSUE THREAD

**Issue by abstracthat** [jenius/axis#174]
I know you have a very simple `border-box()` mixin in `vendor.styl` but I think most of us need to border-box everything on pretty much every project.

http://www.paulirish.com/2012/box-sizing-border-box-ftw/

```stylus
border-box-html()
  html
    box-sizing border-box

  *, 
  *:before,
  *:after
    box-sizing inherit
```

**Comment by jenius** [comment]
Yup, I'd use that. PR it in!

**Comment by abstracthat** [comment]
Where do you want this... `reset.styl`?

**Comment by jenius** [comment]
Hmm I think I'd go with `utilities`

**Comment by abstracthat** [comment]
ok. coming soon...
