### ISSUE TITLE
Links to nib documentation broken

### ISSUE THREAD

**Issue by dbox** [jenius/axis#175]
@jenius  several links to nib's documentation are broken on axis documentation site.

Thanks for all the hard work. We are really loving the roots / stylus / nib / axis / jeet / rupture flow.

**Comment by dbox** [comment]
Trying to fix this and do a pull request. What do I need to do to run the server?

**Comment by hhsnopek** [comment]
Hey @dbox, the axis site repo is here: [jenius/axis-www](//github.com/jenius/axis-www) and uses [roots](//github.com/jenius/roots) to watch and compile the project.

**Comment by dbox** [comment]
You mean roots my favorite thing in the world? Awesome.

**Comment by dbox** [comment]
Sent a pull request. Thanks.

**Comment by jenius** [comment]
:sparkling_heart:
