### ISSUE TITLE
debug() 2.0

### ISSUE THREAD

**Issue by dbox** [jenius/axis#176]
Not sure if something like this already exists, but here is a little mixin I wrote that really helps us with development:

http://codepen.io/dbox/pen/dPzZoE

Might be cool to add to Axis. I don't know if it fits in with the core functionality of Axis, but it's something that our team uses on every project a lot, so thought others might find it helpful.

cc @jenius

**Comment by dbox** [comment]
Basically instead of trying to put borders on everything to see how to edit the layout, you just add dev-mode() to the parent.

**Comment by dbox** [comment]
Actually totally forgot that there is debug mode, but I think this takes it a step further, and I always had issues getting it to work. I'll close for now.

**Comment by jenius** [comment]
I'm ok with having this merged in. Perhaps you could add it to debug mode?

**Comment by dbox** [comment]
Okay I'll give it a try. I haven't figured out how to run the server yet for this

**Comment by jenius** [comment]
You mean for the tests? You can just run `npm test` and it should take care of it :grinning:

**Comment by dbox** [comment]
Thinking about this one. I finally realized that `debug()` has to be run at the root level of css. My dev-mode borders can be run anywhere and it automatically knows the children, grandchildren, etc.

Were you thinking I totally replace `debug()` with mine or find some sort of happy medium?

**Comment by dbox** [comment]
Happy to add it as a secondary tool as `dev-mode()` as well, but I defer to what you'd prefer to see here.

**Comment by jenius** [comment]
You can merge it as the same, just maybe keep the borders as bright red if there are errors?

**Comment by dbox** [comment]
I think these are 2 separate solutions to a common end goal. While I enjoy my approach better, I don't think merging them is the solution because the whole point of mine is that it doesn't have to be run on root, which debug() does.

So unless you're cool with `dev-mode()` added as a second tool (which i'd use like crazy),feel free to close this one out.

**Comment by abstracthat** [comment]
I'd use dev-mode() or maybe call it debug(). I usually use the b() mixin for this presently. But this mixin would be more useful.

**Comment by jenius** [comment]
I'm not attached to needing the current debug to be run on root. I think it's better if it doesn't have to be run on root. As long as it *can* be run on root!

**Comment by dbox** [comment]
Okay, working on this one too.

**Comment by dbox** [comment]
Okay check it, I think I have debug() 2.0 ready to go:

http://codepen.io/dbox/pen/GJZzYo

- call mixin on any element
- all general layout borders are neutral/cool colors to contrast with the error/warnings which are red/yellow
- The 5px borders for flagged content was, ironically, throwing off the layouts, so I've now replaced with:
  - border + filters for images
  - border + background colors for links

Let me know any feedback. Thnx!

**Comment by abstracthat** [comment]
I like this quite a bit! Looking forward to using it.

**Comment by dbox** [comment]
@jenius: Random question: I use Jeet on a lot of sites and they have a debug() as well, which seems to be overwriting the axis one. The problem is I think the way roots is set up I always have to call axis first right, since jeet is imported in the stylus file? Wondering what best way around this is. Could easily add an alias I guess..

**Comment by dbox** [comment]
nm, manually importing axis in stylus after jeet worked. just liked how i didn't have to even import it, but all good.

**Comment by declandewet** [comment]
@dbox You can do this:

```coffeescript
stylus:
  import: ['jeet']
  use: [jeet(), axis()]
```

**Comment by dbox** [comment]
Oh cool. Thanks! 

What's the difference in `import` and `use`? Seems like if I'm using it, it should know I want to import it.

**Comment by hhsnopek** [comment]
`use` will pass your stylus through the plugin, `import` will import it into your stylus file. (if I'm not mistaken @declandewet )

**Comment by dbox** [comment]
So why does axis not need import?

**Comment by hhsnopek** [comment]
because when it's in `use`, stylus parsers/passes your stylus through both axis and jeet and change the mixins and variables based on what's listed first in `use`. Jeet just requires you to `import` it as well. Not sure why...

**Comment by abstracthat** [comment]
Because axis imports itself and jeer doesn't. Have a look at axis' index.js. 

```
    if (implicit) {
      style.import('nib');
      style.import('axis');
```

**Comment by declandewet** [comment]
@hhsnopek You are correct :) And so is @abstracthat - Jeff and I like to do implicit importing - this is useful when using plugins through a JS API, but for some environments, e.g. CodeKit / Prepros, it's better to import explicitly as they don't all support a JS API.

**Comment by jenius** [comment]
Also if you don't like the auto import, you can just call axis with `{ import: false }` and it will disable this :grinning:

**Comment by dbox** [comment]
Oh, I like it! Just thought jeet should too. Basically anything that I'm
using should be imported.

**Comment by abstracthat** [comment]
For the record, if you set `implicit: false` you need to import nib manually. Actually I think we should drop nib since auto-prefixer is a more robust solution.

**Comment by dbox** [comment]
i'd be up for the discussion. I don't really use any of the nib stuff.

**Comment by dbox** [comment]
Slightly off topic, but relavent: @declandewet @abstracthat @jenius are you guys still pretty all-in on stylus, or feeling the need to move to post-css?

I really **LOVE** the stylus/axis/rupture setup. Feels like my perfect setup honestly. Just want to be sure that it's going to be around for a while. I don't want to port all these mixins again.

**Comment by abstracthat** [comment]
I'm all in with it personally... My [boilerplate](https://github.com/abstracthat/site-lightning) uses it and I am maintaining a [few](https://github.com/abstracthat/downbeat), [small](https://github.com/abstracthat/stylus-lightning), [libraries](https://github.com/abstracthat/happy-grid) with it. 

I can understand the merits of postcss too though. Stylus just feels like a good fit with jade and coffeescript so I'm sticking with it. I haven't seen anything quite as clean in the postcss setup.

**Comment by declandewet** [comment]
@dbox Having experimented with switching straight to PostCSS, I'm not so sure I'm actually comfortable using PostCSS as a replacement for a CSS preprocessor. I mean, you *could*, but people tend to stick to using it just to pollyfil future CSS features - there's a huge notion of "sticking to the spec" and not deviating from what will eventually be standard CSS syntax in that community, and there just aren't enough plugins to give all the same features of a CSS preprocessor right now (and I am fully aware that with time, this might change).

That being said, I'm totally all about using PostCSS *and* Stylus. PostCSS is so fast it barely makes a difference to compile time, and there are plenty of valid use-cases for post-processing, for example, producing an automatic RTL stylesheet without much thought, generating a style guide, and better CSS optimisation / minification / deduplification.

Also, I'm actually busy making a PostCSS plugin at the moment - and I've found that combining Stylus and PostCSS is pretty cool - Stylus plugins can hook into Stylus' `end` event, which gives access to the CSS source right before the compiled file is written - this allows one to effectively *use PostCSS as a stylus plugin*. I don't even need to explain why that's awesome.

**Comment by jenius** [comment]
Yeah I'm ok with dropping nib as well honestly. It's not maintained at the moment. It would just be a bit of work to re-import some of the functions that we moved over there back in the day when we thought it would be maintained and made it a dependency. Perhaps we should open this up as a separate issue to get organized as far as what kind of work we're looking at to remove it?

For postcss, I haven't messed with it much, but I know autoprefixer is now used through it and this is how the `autoprefixer-stylus` plugin works, which works perfectly fine with stylus in exactly the way declan described above. We also have a roots extension for postcss and support for it in accord, so welcome to experiment with either or both!
