### ISSUE TITLE
Vertically align reset?

### ISSUE THREAD

**Issue by dbox** [jenius/axis#177]
I find myself using this a lot:

```
vertically-align-reset()
  position relative
  top auto
  transform translateY(0)
```

Is there someway that `vertically-align()` could be edited so that passing `vertically-align(reset)` would do the above?

**Comment by jenius** [comment]
Yeah maybe we could have passing `false` to vertically-align make it reset?

**Comment by dbox** [comment]
That'd be great. I'm not sure how to write it but I can research it, unless you know off the top of your head.

**Comment by jenius** [comment]
Just pull down the source code, do a search for `vertically-align`, bam there it is :grinning:

**Comment by dbox** [comment]
Haha. No, i got that I meant writing the mixin itself passing the conditional. But i'll figure it out.

**Comment by jenius** [comment]
Oh just run an if-else check right at the beginning for that parameter. If false, run the reset, else do it normally.

**Comment by dbox** [comment]
Think I got it:
http://codepen.io/dbox/pen/jPPrKW

**Comment by jenius** [comment]
Looks good to me! PR that in : )
