### ISSUE TITLE
has no method 'forEach'

### ISSUE THREAD

**Issue by seleckis** [jenius/axis#186]
Tried to use axis within Grunt, but got error, while compiling stylus files:
```
Warning: Object function (style){
    style.use(nib());         // include nib
    style.include(__dirname); // include axis

    if (implicit) {
      style.import('nib');
      style.import('axis');
    }
  } has no method 'forEach' Use --force to continue.

Aborted due to warnings.
```
My Grunfile:
```js
module.exports = function(grunt)
{
	var axis = require('axis');
	...
	stylus: {
			main: {
				options: {
					compress: false,
					use: axis()
				},
				files: [{
					src: 'app/main.styl',
					dest: 'dist/css_temp/main.css'
				}]
			},
		},
	}
	...
}
```
Any suggestion?

**Comment by jenius** [comment]
You need to put axis in an array under `use`, as such:

```
options: {
                    compress: false,
                    use: [axis()]
                },
```

This is not an axis issue, it's a grunt usage issue, but that will almost certainly solve it.  Hope you enjoy axis!

**Comment by seleckis** [comment]
Didn't help. :(
`Warning: Cannot call method 'use' of undefined Use --force to continue.`

**Comment by jenius** [comment]
Not sure what to tell you, I don't use grunt. This is not an axis issue though. I might try looking up some example configs or asking in a grunt community!

**Comment by seleckis** [comment]
This one worked correct:
```js
options: {
  compress: false,
  use: [axis]
}
```

**Comment by jenius** [comment]
Awesome, glad you got it working!
