### ISSUE TITLE
equal-widths()

### ISSUE THREAD

**Issue by dbox** [jenius/axis#187]
@jenius feel free to veto this. Here's another thing I use all the time in my mixins based on this idea:

http://lea.verou.me/2011/01/styling-children-based-on-their-number-with-css3/

My mixin isn't super portable at the moment but I could probably write it to be, but I may need some help.

Let me know if you want it. 

@abstracthat you ever use anything like this?

**Comment by declandewet** [comment]
@dbox I actually like the syntax used in [postcss-quantity-queries](https://github.com/pascalduez/postcss-quantity-queries) a whole lot. You can do stuff like `.some-selector:at-least(3)` or `.some-selector:exactly(4)` or `.some-selector:at-most(2)`. Perhaps the same grammar can be applied to Stylus mixins:

```stylus
.some-selector
  +exactly(4)
    color: blue
```

**Comment by dbox** [comment]
@declandewet That'd be great. Think it is possible? I was originally thinking of some rewrite first comment on that page i sent:

sass:
```
@for $i from 1 through 4 {
  li:first-child:nth-last-child(#{$i}),
  li:first-child:nth-last-child(#{$i}) ~ li {
    width: 100% / #{$i} } } 
```
Where you'd pass variables for li and the number.

**Comment by dbox** [comment]
But clearly your approach would be way more flexible. Just don't think I could write that.

**Comment by jenius** [comment]
I think this would be a nice axis module as well. It's small enough that I feel like it doesn't warrant an entirely separate library, but still a nice little utility

**Comment by abstracthat** [comment]
That would be an awesome mixin. It looks easy enough to adapt based on the thorough documentation at https://github.com/pascalduez/postcss-quantity-queries#api.

**Comment by dbox** [comment]
@abstracthat you want to take a stab at it?

**Comment by abstracthat** [comment]
```stylus
at-least(count = 3)
  &:nth-last-child(n+count),
  &:nth-last-child(n+count) ~ li
    {block}
```

**Comment by dbox** [comment]
`li` should be passed as variable too right?

**Comment by abstracthat** [comment]
I don't think so. You would use it on your ul > li as a block mixin, pass your styles underneath.

**Comment by abstracthat** [comment]
I think this would work for the four in that library. Thanks @declandewet for mentioning that excellent library.

```stylus
at-least(count = 4)
  &:nth-last-child(n+count)
  &:nth-last-child(n+count) ~ li
    {block}

at-most(count = 4)
  &:nth-last-child(-n+count):first-child
  &:nth-last-child(-n+count):first-child ~ li
    {block}

between(start, end)
  &:nth-last-child(n+start):nth-last-child(-n+end):first-child
  &:nth-last-child(n+start):nth-last-child(-n+end):first-child ~ li
    {block}

exactly(count)
  &:nth-last-child(4):first-child
  &:nth-last-child(4):first-child ~ li
    {block}
```

**Comment by dbox** [comment]
what if you wanted to use it on something besides lis ?

**Comment by dbox** [comment]
that was quick. :)

**Comment by abstracthat** [comment]
that's what `&` is picking up.

**Comment by abstracthat** [comment]
I'll draft the PR to a branch, if you want to add tests / doc for it. I'm a little short on time for that currently.

**Comment by dbox** [comment]
yeah, definitely. I guess i'm still confused about the `li` at the end of the second line. Isn't that hardcoded?

**Comment by abstracthat** [comment]
Oh, yeah... oops.

**Comment by dbox** [comment]
I think it's fine to default to `li`s

**Comment by abstracthat** [comment]
is there a way in stylus to get just the first parent with `&`?

**Comment by dbox** [comment]
I don't think so. That's the ultimate dream right?

**Comment by dbox** [comment]
Actually maybe,  i don't know

**Comment by dbox** [comment]
would selector() do the trick somehow? https://learnboost.github.io/stylus/docs/selectors.html

**Comment by dbox** [comment]
maybe i'm reading it wrong but seems like you could just replace that last li with selector()

**Comment by abstracthat** [comment]
I can't mess with it right now. We might also want to bake in the width calculation. This library doesn't seem to do that. It is more for just making the selector.

**Comment by dbox** [comment]
It's super helpful just to have the selectors,  then we could make a separate mixin that uses the selectors with the width calculations.

**Comment by dbox** [comment]
Thanks for the help!

**Comment by abstracthat** [comment]
Yeah, I agree. More modular. Something like 

```stylus
equal-widths(count = 4)
  width (1 / count)
```

**Comment by dbox** [comment]
will `between` have conflicts with rupture?

**Comment by abstracthat** [comment]
yeah, maybe namespace them all in `select-`.

**Comment by dbox** [comment]
perfect. this will be awesome.

**Comment by dbox** [comment]
Actually now that I think about it I"m not sure select is the right term, but should be name-spaced regardless.

@abstracthat feel free to mess around with this pen. For some reason not working yet.

http://codepen.io/dbox/pen/waeQOL

**Comment by dbox** [comment]
the code works but for some reason it's not passing the variable: https://www.dropbox.com/s/03z9l4k2zd77l6p/Screenshot%202015-06-12%2016.50.21.png?dl=0

Still looking into

**Comment by declandewet** [comment]
So, there's actually a [bug](https://github.com/stylus/stylus/issues/1703) in Stylus right now where `selector()` doesn't quite work as it supposedly should :(

Normally, you might do something like this (but do note it does not work right now)

```
+at-least(count)
  nodes = split(' ', selector())
  index = length(nodes)
  target = nodes[index - 1]
  parent = nodes[index - 2]
  {parent} > {target}:nth-last-child(n+{count})
  {parent} > {target}:nth-last-child(n+{count}) ~ {target}
    {block}
```

However, it is possible to pass the target as an argument: 

```
at-least(count, nodes...)
  & > {nodes}:nth-last-child(n+{count})
  & > {nodes}:nth-last-child(n+{count}) ~ {nodes}
    {block}

ul
  +at-least(3, li)
    color: blue

/*
ul > li:nth-last-child(n+3),
ul > li:nth-last-child(n+3) ~ li {
  color: #00f;
}
*/
```

**Comment by dbox** [comment]
:+1: :+1: on it. Thanks @declandewet !

**Comment by dbox** [comment]
Pretty sure this is totally going to work.

1. I didn't realize I had to wrap count in {count}
2. @declandewet - For whatever reason codepen won't run any code that has "nodes" in it. Is that the exact term for referencing selectors, or can I use any word there?
3. @abstracthat - pulling `equal-widths` out into it's own separate thing seemed like a good idea, but how can we pass the number value from the block mixin to it?

**Comment by dbox** [comment]
Awesome. Moved all the quanity query stuff to #189. That's going to be great, but got a little sidetracked from the original mission here getting back to this:

equal-widths(count = 4)
  width unit((100 / count), '%')

I still think it's going to have to be some sort of for loop similar to this (which I haven't rewritten yet):

```scss
@for $i from 1 through 4 {
  li:first-child:nth-last-child(#{$i}),
  li:first-child:nth-last-child(#{$i}) ~ li {
    width: 100% / #{$i} } } 
```

Because the css has to have all the options already rendered out, since you dont know how many siblings there are.

**Comment by declandewet** [comment]
@dbox `nodes` can be any variable :)

**Comment by dbox** [comment]
@declandewet thanks. Updated codepen ... What is the "..." for? Seen it used just never knew.

**Comment by dbox** [comment]
Just allow multiple variables in that one spot?

**Comment by dbox** [comment]
Okay super close on this just have one question. Can you guys take a look:

http://codepen.io/dbox/pen/waqKWx

We need to bake in gutter to the mixin (ala jeet) othewise margins will make it more than 100%.

I want to do something like the following:

```stylus
calc(width unit((100 / count), '%') - gutter)
```
but I can't figure out the proper syntax. Any ideas?

**Comment by dbox** [comment]
//cc @corysimmons :dancers:

**Comment by corysimmons** [comment]
You rang?

**Comment by dbox** [comment]
Trying to figure out syntax how do to calc with that line above in codepen (what I was trying to do is commented out)

**Comment by dbox** [comment]
Well this got a lot crazier than I expected but I have it working with gutter:

http://codepen.io/dbox/pen/pJrROo

Notes:
- I'm sure needs major code vetting cleanup. I'm just a designer, so go easy on me :)
- Need to fix it so gutters can pass px, %, em, or rem. Don't know how to do that yet.

**Comment by dbox** [comment]
Been talking with @corysimmons. Sounds like he's down with getting this into Lost grid. I'm fine to use it there.  Definitely feels better to have it be part of the grid system. 

@jenius if you still want in Axis I will add, but I'm fine with closing this out and leaving these examples for anyone who might have a use for them:

My solve:
http://codepen.io/dbox/pen/pJrROo?editors=110


@declandewet 's  solve:
http://codepen.io/declandewet/pen/BNYwpE?editors=010

**Comment by jenius** [comment]
Sounds fine with me, this seems like the kind of thing that belongs in a grid system to me.

**Comment by corysimmons** [comment]
If you're still interested in adding this to Axis I made a `table` version that seems pretty clean: http://codepen.io/corysimmons/pen/jPpvay?editors=110

**Comment by declandewet** [comment]
@corysimmons mine uses the same technique bit with the addition of `table-layout: fixed` and I opted for margin over horizontal border spacing as the spacing seems off by a pixel or two in some cases

**Comment by corysimmons** [comment]
Yeah I noticed it was off a pixel at various sizes.

Your solution still seems to use `border-spacing` instead of margins. Am I missing something?

![](http://i.imgur.com/XSlENHm.png)

What's the advantage of `table-layout: fixed`?

**Comment by corysimmons** [comment]
Maybe we should take this chit-chat to https://gitter.im/jenius/axis ?

**Comment by declandewet** [comment]
I use border-spacing for vertical gutters and margin for horizontal :) There are a number of benefits for `table-layout: fixed` - mainly fixes cell width for long text but it also improves layout rendering speed. There's way more on the subject at these links:

https://css-tricks.com/fixing-tables-long-strings/
http://colintoh.com/blog/display-table-anti-hero
http://tympanus.net/codrops/css_reference/table-layout/

**Comment by dbox** [comment]
So, I've been thinking about this. I think where this goes off the rails for Axis is the gutters - makes everything much more complex, + competes with any grid system being used.

However, having an easier way to do table layout is definitely useful. I think maybe we just add something like this:

Table layout mixin:
http://codepen.io/dbox/pen/pvrZZV

... and leave everything else up to the grid systems.

**Comment by abstracthat** [comment]
I like that `tl()`. Simple and extendable.

**Comment by jenius** [comment]
Yup, I can get down with that :+1:

**Comment by dbox** [comment]
Thanks to everyone on this thread. Yielded some great stuff. :tada:
