### ISSUE TITLE
Mixin Quantity Queries

### ISSUE THREAD

**Issue by dbox** [jenius/axis#189]
```stylus
// Mixin Quantity Queries

quantity-at-least(count=4, selector=li)
  & > {selector}:nth-last-child(n+{count})
  & > {selector}:nth-last-child(n+{count}) ~ {selector}
    {block}

quantity-at-most(count=4, selector=li)
  & > {selector}:nth-last-child(-n+{count}):first-child
  & > {selector}:nth-last-child(-n+{count}):first-child ~ {selector}
    {block}

quantity-between(start=0, end=10, selector=li)
  & > {selector}:nth-last-child(n+{start}):nth-last-child(-n+{end}):first-child
  & > {selector}:nth-last-child(n+{start}):nth-last-child(-n+{end}):first-child ~ {selector}
    {block}

quantity-exactly(count=4, selector=li)
  & > {selector}:nth-last-child({count}):first-child
  & > {selector}:nth-last-child({count}):first-child ~ {selector}
    {block}

// usage
ul.least
  +quantity-at-least(2)
    border: 1px solid blue 
```

demo here:

http://codepen.io/dbox/pen/waeQOL

I'll get these PR'd in soon. Thanks to @declandewet and @abstracthat

**Comment by jenius** [comment]
Awesome, really nice work here!

**Comment by dbox** [comment]
@declandewet check codepen. okay with name `selectors...` instead of `nodes...`?

**Comment by dbox** [comment]
actually I think i'm going to redo it to be `selector=li` so it defaults to `li`

**Comment by abstracthat** [comment]
This is awesome. Great job!

Personally I still feel `select-` is a more natural namespace. We are building selectors. And the individual mixin names (at-least,exactly...) imply that we are working with quantities. I think it reads better that way. But I'm fine with just adding some aliases in my settings file if no one agrees with me. :)

**Comment by dbox** [comment]
I think select will get confusing, especially with `between` because I'd assume if i did `select-between(2,-6)` it'd only target those specific ones. I'm open ..
