### ISSUE TITLE
New categories / utilities cleanup

### ISSUE THREAD

**Issue by dbox** [jenius/axis#191]
@jenius The `utilities` folder seems pretty unwieldy to me. Should we:

Move the following to `typography`: 
- `bold()`
- `italic()`
- `normal()`
- `raquo()`
- `font-face()`

Create `images` (media?) category and move the following over:
- `bg()`
- `bg-retina()`
- `image-replace()`
- `sprite()`
- `cached-image-url()`
- `cached-image()`

Create a `layout` category and move the following over:
- `columns()`
- `avoid-column-break()`
- `group = clearfix`
- `inline-block()`
- `vertically-align()`
- `media()`
- `ratio-box()`

Move  `border-box-html` to `reset`

Which would leave the rest feeling very much like utilities:
- `pie()`
- `rounded()`
- `no-select()`
- `b()` (Could go in layout I suppose)
- `triangle()`
- `debug()`
- animation timing functions
- `rem()`
- quantity queries

Thoughts? Moving stuff around shouldn't have any compatibility issues should it?

**Comment by jenius** [comment]
Agreed, I think those moves you suggested are appropriate, and it will not cause any breakage or issues, just general organization. Feel free to PR this guy in :+1:

**Comment by dbox** [comment]
So here's what I'm thinking:

**0.4.1** - I can bump this today
 - rem calculator
 - quantity queries

**0.4.2**
 - folder re-organization per above.
- `even-widths` - I have this ready to go (see #187) but it needs some @jenius (or @declandewet or @abstracthat ) - style code cleanup to to be up to snuff

**0.5.0** - major breaking changes
- drop nib
- add auto-prefixer as dependency, right?

//cc @ccampb13

**Comment by jenius** [comment]
Looks like a solid plan to me. Although I don't want to add autoprefixer as a dependency. I feel like it should be up to the user whether they want to use autoprefixer. We could perhaps include it as a convenience option that's off by default, but I don't want to force it. However I am not set in stone so if you have a compelling reason I could be convinced otherwise!

**Comment by dbox** [comment]
Basically the only thing I get hung up on when running tests is the vendor prefixes. So was hoping it'd make that easier, but i'm fine either way.

**Comment by dbox** [comment]
Also, just worried how much of nib's vendor prefix stuff it's currently using.

**Comment by jenius** [comment]
Yeah, I'm entirely ok with running the tests without vendor prefixes. I just don't feel like prefixing is our job anymore. Autoprefixer is great at taking care of this, so we should just leave it to them entirely.

**Comment by jenius** [comment]
We'll just have axis output solid modern css, and let AP take care of old browsers and such

**Comment by dbox** [comment]
Great. Still not looking forward to all the tests :) But sounds like @abstracthat is down for helping out and I believe @ccampb13 is as well.

**Comment by ccampb13** [comment]
@jenius, Working on setting up testing for the scss port of axis and
running into an issue. In test/fixtures/*.styl files, you are calling the
mixin. When I attempt to do the same I receive a "no mixin named `button`"
error. Where in the setup do you import the mixins from axis/*.styl to be
used in the test directory?

On Tue, Jun 16, 2015 at 2:23 PM, Daniel Box <notifications@github.com>
wrote:

> Great. Still not looking forward to all the tests :) But sounds like
> @abstracthat <https://github.com/abstracthat> is down for helping out and
> I believe @ccampb13 <https://github.com/ccampb13> is as well.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jenius/axis/issues/191#issuecomment-112535833>.
>



-- 
Chad Campbell
615-429-2280

**Comment by declandewet** [comment]
@ccampb13 that would be here: https://github.com/jenius/axis/blob/master/test/test.coffee#L13

Axis imports itself using the JS API: https://github.com/jenius/axis/blob/master/index.js#L14

I don't think there's an equivalent way of doing implicit importing in Sass, so you have carte blanche on how you want to handle that

**Comment by ccampb13** [comment]
thanks @declandewet, stylus continues to impress

**Comment by dbox** [comment]
@jenius @abstracthat Should `border-box-html` be part of the new `layout` or part of `reset`?

**Comment by abstracthat** [comment]
It’s a reset utility when applied globally I would say.
