### ISSUE TITLE
Drop nib

### ISSUE THREAD

**Issue by dbox** [jenius/axis#192]
@abstracthat proposed the idea. @jenius seemed on board. Starting the discussion:

Seems like we're all using auto-prefixer these days, and I saw a complaint about nib compile time vs auto-prefixer anyway.

What all do we need  to keep from nib if we drop it?

- reset
- gradients
- position
- border-radius
- ellipsis
- size
- clearfix

I'm happy to help bring over any of the individual mixins like `ellipsis` that would be handy, but honestly I don't use any of it, even the gradients.

**Comment by jenius** [comment]
I'm just going to edit your top post and add to this list

**Comment by abstracthat** [comment]
transition is being used to. I can help with this if needed but I am traveling for the next week and a half so I'll see where you guys are at when I get back.

**Comment by dbox** [comment]
Transition is being used in current axis mixins?

**Comment by dbox** [comment]
We should just use auto prefixer version, no?

**Comment by dbox** [comment]
I think auto-prefixer will take care of border radius as well.

**Comment by abstracthat** [comment]
Yeah you can just remove that line that caches nib transition as _transition I think.

**Comment by dbox** [comment]
So I learned a lot while doing #209 about how Nib is integrated. It's not really used in *that* many mixins but the ones that do use is are pretty intertwined - mostly because of vendor issues.

The only real challenges of extracting it are the gradients (Which are overwrought/outdated in Nib anyway) and the `support-for-ie` stuff - (Maybe it's time to move on? IE9 support is plenty imho and even that is generous.)

The thing that would benefit us the most as the next-step would be to eliminate most/all the `vendor.styl` and update the test suite to not test against vendor styles. **I need help on this one, as I know nothing about setting up tests.** Then, getting `visual-test.html` able to use autoprefixer.

After that is done I can go in rework gradients in the specific mixins and we'd have a version of Axis completely non-dependent on Nib (which I have my doubts will ever get future-proofed for Stylus 1.0 anyway - and even if it did, it would mean lots of testing and rewrites for us.).

Now, where we might disagree is on how much of Nib to put back, but we can discuss that more after this step. :)

**Comment by jenius** [comment]
I'm entirely ok with eliminating all support for gradients other than the official spec. Autoprefixer will take care of fixing this stuff. This shouldn't cause any breaking changes I don't think, as long as autoprefixer is being used.

I'll take a look at getting autoprefixer integrated in to the visual tests today. Is there anything else I can help with here?
