### ISSUE TITLE
rem(value) is a function not mixin

### ISSUE THREAD

**Issue by dbox** [jenius/axis#194]
Putting here for myself

**Comment by dbox** [comment]
I noticed all the other functions start with a dash. Is this preferred? When I add a dash it fails tests..

**Comment by declandewet** [comment]
We use that as a convention to differentiate functions from mixins. Not sure why it would fail tests though...

**Comment by dbox** [comment]
Actually testing is failing on anything i do now, even super simple tests...

**Comment by jenius** [comment]
Hey sorry for the late followup, but has the testing issue been resolved? If not I'll take a look at this today
