### ISSUE TITLE
Update variable names / future-proofing

### ISSUE THREAD

**Issue by dbox** [jenius/axis#201]
I think we tackle this before #192.

Per conversation on https://github.com/declandewet/stylus-conventions/issues/8#issuecomment-124158817

We need to:

- [x] Add `$` to all variables
- [x] Unify all variable names to be `$dash-case`
- [x] ~~Reference @declandewet's conventions doc in contributing?~~

**Comment by declandewet** [comment]
I'm not so certain, my conventions doc has gone seriously unmaintained because of my limited time to devote to open source at my current job

**Comment by dbox** [comment]
FWIW I think the community needs such a doc, but i'm fine to cross off #3.

**Comment by dbox** [comment]
I have this almost done. It was not trivial. Post update on this soon.

**Comment by dbox** [comment]
Done in #209 

Probably should make this **v0.5.x*. Not sure if there would be any breaking changes but better safe than sorry. 

So up next **v0.4.3**:
- adds `rule()`
- adds `hover-glow()` and `hover-float()`
- adds `click-down()`,` click-inset()`, `click-shadow()`, & `click-shrink()`
- moves `print` to `reset`

**v0.5.0**
- new variable structure.

**v0.5.1**
- select-box()
- ??
- ??

Then we'll push dropping nib to **v0.6.x*

**Comment by jenius** [comment]
Good roadmap. I'm going to get some stuff merged today, sorry for the delays!

**Comment by dbox** [comment]
Honestly I didn't expect the nib removal to go so quickly. Not sure we even really need to have new variable structure be it's own release now. We can just roll it out with the sans-nib update.
