### ISSUE TITLE
Stagger

### ISSUE THREAD

**Issue by abstracthat** [jenius/axis#202]
I had to make one of those rippling animation trails today. This mixin works nicely for that. We could probably make one for transition too. The downside is you have to know how many children there are and it maybe makes a lot of `:nth-of-type` rules, though I don't know of a better way for this use case.

http://codepen.io/anon/pen/oXajxL

**Comment by dbox** [comment]
Nice! yeah, stuff like this comes up a lot. 

However, we'd definitely be opening pandora's box a bit if Axis became the place for default animations as well.

Up to @jenius obviously, but I'm thinking maybe a separate animation library is the place. I always roll my own per project, but a clean little importable library would be awesome, and I would definitely contribute to it. Seems like it'd be a perfect fit into your Site Lightning setup :)

**Comment by abstracthat** [comment]
Sounds good. I'll file this away in my random mixins file and see about building something out for animations soon.

**Comment by dbox** [comment]
I want a peek at that random mixins file :dancer:

**Comment by jenius** [comment]
Yeah, I would agree that animations are their own game. There are a bunch of libraries out there, but I usually also roll my own smaller version. Maybe we could start a separate library to house animations? I'd be happy to contribute what I can!

**Comment by dbox** [comment]
Let's do it.

**Comment by dbox** [comment]
Ignore the scss for now but maybe something like this is a good start?

http://codepen.io/dbox/pen/ZboVOg

For me when dealing with animations I usually use classes, not just straight css

``` jade
div.animated.fade-in-up
  p I'm animated
````

Could maybe have some sort of settings on which animations actually get rendered out in the  additive mixin.

Thoughts? @jenius @abstracthat

**Comment by jenius** [comment]
I like this, cool idea :+1:
