### ISSUE TITLE
Question: automated render as one stylus file?

### ISSUE THREAD

**Issue by dbox** [jenius/axis#208]
Still waiting to hear back from Codepen guys about getting Axis added as an official add-on. 

In the meantime:

Is there some way to automate rendering all the individual  `.styl` files into one master file (non-compiled)? Would make updating this http://codepen.io/dbox/pen/rVZPKo much easier.

**Comment by dbox** [comment]
And I don't mean to replace any of the current system, just a one-off axis-all.styl that I could import into codepen

**Comment by declandewet** [comment]
This is kind of possible with a build step... Basically, hit the main file, replace any `@import` statements with the contents of the file at the path the import statement refers to using the current file's path as a context...

However, this becomes tricky when you consider `@import`s that are from `node_modules` as well as Stylus plugins that make use of the JS API - there's no way to include this logic in a static stylus file (nib makes heavy use of the JS api)

**Comment by dbox** [comment]
k. thanks @declandewet!

**Comment by dbox** [comment]
@declandewet FWIW I did some more research on this and realized we can do it from command line:

`cat *.styl >> output.styl`

of course we probably wouldn't want that file to live in the production folder..

**Comment by dbox** [comment]
** excluding `index.styl`
