### ISSUE TITLE
button font-family

### ISSUE THREAD

**Issue by robmoggach** [jenius/axis#212]
Please add font-family to the `button()` mixin.

**Comment by dbox** [comment]
IMHO this doesn't belong in the button mixin. The button should just cascade the font from it's parent. You can just do something like:

```html
<a href="#" class="btn serif">Sample Button</a>
```

``` stylus
.btn
  button()
  &.serif
    font-family: georgia, serif
```

**Comment by jenius** [comment]
Agreed.
