### ISSUE TITLE
Retina Image Handling

### ISSUE THREAD

**Issue by jenius** [jenius/axis#214]
So I just want to open up a discussion about how we want to do retina images with axis.

Nib has a mixin that will postfix `@2x` to a background image, then add this inside a `min-resolution` media query. We currently have one that takes a double size image and scales it down to work for both normal and retina. I feel like somewhere in between these two there is an ideal solution.

If I were doing a little readme-driven development, I would want:

- if passed a normal size image, and a retina image is present, adds this in a resolution media query
- if passed a double size image, scales it down for normal and uses for both
- allows width and height to be passed, but does not strictly require them. when their absence would cause a display issue, warns the user
- allows other background properties to be passed through, so they are not overridden by the mixin

Anyone else have thoughts on this?

**Comment by dbox** [comment]
This sounds great to me.  However I'm not the target market for this one. I've pretty much stopped creating 2 versions of images now and just create the @2x asset. 

- with large bgs (jpgs) you can actually crush the @2x to a smaller file size than the @1x because it can have more compression without being noticeable 
- most pngs aren't huge issue either once crushed (ps: roots png crush needed :) )
- often I'll need different cropping of same image for different media queries , so having more resolution helps. 

Happy to help out however we land.

**Comment by jenius** [comment]
Generally, I agree. I typically just use the 2x asset as well, which is why the `bg-retina` mixin exists. However, I must admit that it can potentially save load time to serve a 1x asset to non-retina screens, and it shouldn't be super difficult either if contained within a resolution query.

Can you link me to more info on the getting 2x to smaller file size than 1x piece? If this can be consistently replicated, then that's a fair enough reason to ignore 1x for us I think.

**Comment by dbox** [comment]
Yeah I'm totally fine to do it exactly as you've spelled out. I'll post
some examples later today or tomorrow.

**Comment by dbox** [comment]
http://codepen.io/dbox/pen/PPmPaW

**Comment by jenius** [comment]
Cool, this is great. Perhaps we should write up a short guide like this and present it alongside the `bg-retina` mixin as a suggestion for users :grinning:

**Comment by dbox** [comment]
Sure. Can do.

**Comment by jenius** [comment]
You are my hero :pray:

**Comment by dbox** [comment]
http://axis.netlify.com/#bg-retina

You want writeup here, in the comments in the code or both?

**Comment by jenius** [comment]
Just on the docs site I think would be best!
