### ISSUE TITLE
button() improvements

### ISSUE THREAD

**Issue by dbox** [jenius/axis#216]
putting this here for myself

- [x] Add `no-select()` 
- [x] Currently background color has to get very dark before text will change to white. Need to look into adjusting tolerance level.

**Comment by jenius** [comment]
Absolutely -- agreed on both!

**Comment by dbox** [comment]
I got this working. Just need to fix the tests and I'll push.

**Comment by dbox** [comment]
Btw is there a reason that disabled button does not have a test?

**Comment by jenius** [comment]
Hah, not that I know of. Seems like an oversight!

**Comment by dbox** [comment]
Having a couple issues getting test to pass on buttons. Figured someone was
like "forget this!"
