### ISSUE TITLE
Stylesheet for documentation is broken.

### ISSUE THREAD

**Issue by Splendorr** [jenius/axis#229]
For the page at http://axis.bitballoon.com,
when I load it, it is unstyled HTML. This has been the case since at least last month, when I figured it was a fluke.

![screen shot 2015-10-17 at 1 46 36 am](https://cloud.githubusercontent.com/assets/150489/10557214/eca1a050-7470-11e5-96e6-230a920d761d.PNG)

**Comment by dbox** [comment]
http://axis.netlify.com is the current location.

**Comment by dbox** [comment]
@jenius looks like the description on axis-www is still pointing to bitballoon. Are they both supposed to be working?

**Comment by Splendorr** [comment]
Oh, good! I just had an old bookmark. Thanks :)

**Comment by jenius** [comment]
No, just netlify. I couldn't find one that points to bitballoon in the repo, but if you have one please PR and fix it! :grin:

**Comment by dbox** [comment]
![image](https://cloud.githubusercontent.com/assets/296130/10563743/e03aa208-755b-11e5-9cab-f333df1586cb.jpeg)m
I just meant here. I'd fix it but I don't have the option to.

**Comment by jenius** [comment]
fixed! good catch, thanks :grin:
