### ISSUE TITLE
Description of ellipses() and hyphenation() the same

### ISSUE THREAD

**Issue by newswim** [jenius/axis#234]
Also the hyphenation example doesn't seem to hyphenate like I would expect it should?

**Comment by dbox** [comment]
Updated description on the docs site.

**Comment by dbox** [comment]
Agree on hyphen not appearing to be working currently.

**Comment by dbox** [comment]
@jenius Chrome doesn't support any hyphenation, so I think this mixin may be a little misleading.

Renaming/deleting it would cause some backwards compatibility issues – not sure how many people use this. 

Probably should:
- note that `lang="en"` is set somewhere on a containing element (required to work - docs site needs it)
- note chrome incompatibility with hyphenation.

**Comment by jenius** [comment]
Yup, agreed. Thanks for catching this
