### ISSUE TITLE
Potentially unhandled rejection

### ISSUE THREAD

**Issue by elpollitodiablo** [jenius/axis#235]
We have a strange parse-error within tables.styl. We're using roots:

    Potentially unhandled rejection [5] ParseError: /Users/daniel/GIT/responsive-template/node_modules/axis/axis/tables.styl:52
     48|     border-collapse: separate
     49|     *border-collapse: collapsed
     50|     border-radius: 4px
     51| 
     52|     th + th, td + td, th + td, td + th
     53|       border-left: 1px solid #ddd
     54| 
     55|     thead:first-child tr:first-child th
     
    unexpected ","

**Comment by dbox** [comment]
I just ran a basic table test on a clean roots install and isn't throwing any errors. Can you provide a simplified example recreating the problem?

**Comment by dbox** [comment]
@elpollitodiablo question were you using axis with express?

**Comment by elpollitodiablo** [comment]
well, I'm no longer working on that project, but as far as I remember we weren't. But we were using Jeet and [Roots](http://roots.cx) and I'm not sure about them

**Comment by dbox** [comment]
i think this is related to an old version of stylus. I'm going to close this for now. Let me know if it ever resurfaces.
