### ISSUE TITLE
update documentation for express 4.x

### ISSUE THREAD

**Issue by devgg** [jenius/axis#245]
Under http://axis.netlify.com/#usage / Express

    var app = express()

    app.middleware({

Express does not have the `middleware()` function anymore.

I tried the following:

    var express = require('express');
    var stylus = require('stylus');
    var axis = require('axis');

    var app = express();

    app.use(stylus.middleware({
        src: config.paths.views,
        dest: config.paths.public,
        compile: compile
    }));

    function compile(str, path){
        return stylus(str)
            .set('filename', path)
            .use(axis());
    }

Which gives me a 500 error when I try to request the stylesheet.
When I comment out the last line like this:

    function compile(str, path){
        return stylus(str)
            .set('filename', path);
    //        .use(axis());
    }

Everything works fine.

If I am missing something please document the right way to use axis with express 4.x.

**Comment by devgg** [comment]
Upon further investigation I found the problem?!

    var stylus = require('stylus');
    var axis = require('axis');

    stylus('defaultWidth = 580px')
        .use(axis())
        .render(console.log.bind(console));

Gives the following error:

    { [ParseError:<removed>/node_modules/axis/axis/tables.styl:52
       48|     border-collapse: separate
       49|     *border-collapse: collapsed
       50|     border-radius: 4px
       51| 
     > 52|     th + th, td + td, th + td, td + th
       53|       border-left: 1px solid #ddd
       54| 
       55|     thead:first-child tr:first-child th

    unexpected ","
    ]
      name: 'ParseError',
      message: <removed>/node_modules/axis/axis/tables.styl:52\n   48|     border-collapse: separate\n   49|     *border-collapse: collapsed\n   50|     border-radius: 4px\n   51| \n > 52|     th + th, td + td, th + td, td + th\n   53|       border-left: 1px solid #ddd\n   54| \n   55|     thead:first-child tr:first-child th\n\nunexpected ","\n',
      filename: <removed>/node_modules/axis/axis/tables.styl',
      lineno: 52,
      input: '// ------\n// Tables\n// ------\n\n// Mixin: Table\n//\n// Ported directly from Twitter Bootstrap, ...

**Comment by devgg** [comment]
After changing index.styl from

    @import 'buttons'
    @import 'forms'
    @import 'tables'

to 

    @import 'buttons'
    @import 'forms'
    //@import 'tables'

everything works as expected.

**Comment by devgg** [comment]
Error was resolved in #246. Documentation should still be updated.

**Comment by dbox** [comment]
So what needs to be updated in documentation? (Sorry I don't use Express...and @jenius is traveling)

**Comment by devgg** [comment]
change

    app.middleware({
      src: __dirname,
      dest: __dirname  '/public',
      compile: compile
     });

to 

    app.use(stylus.middleware({
      src: __dirname,
      dest: __dirname  '/public',
      compile: compile
     });
;-)

**Comment by jenius** [comment]
@devgg up for making a pull request to change it?

**Comment by dbox** [comment]
@devgg It would need to be done here: https://github.com/jenius/axis-www

**Comment by devgg** [comment]
@dbox @jenius will do :-)
