### ISSUE TITLE
fix table.styl with stylus 0.42.3 and axis 0.5.2.

### ISSUE THREAD

**Issue by devgg** [jenius/axis#246]
See issue #245

**Comment by dbox** [comment]
are you able to update stylus? 0.42.3 was almost 2 years ago

**Comment by devgg** [comment]
Wow sorry my bad. I auto generated the package.json with WebStorm. Upgrading to stylus 0.53.0 fixed the issue.

**Comment by dbox** [comment]
Sweet! Glad it worked out.
