### ISSUE TITLE
Axis Range overwrites Stylus Range

### ISSUE THREAD

**Issue by MortenHofft** [jenius/axis#261]
I find it unfortunate that valid Stylus is invalid when using the Axis library.

```
$myList = range(50px, 800px, 50)
```
Seemingly it is overwritten by the Axis color range function.

Wouldn't it be better to use another name for the color range that Axis provides. Or is there a workaround I'm not familiar with? Either way I think that leaving Stylus function intact would be the more intuitive solution. Or maybe there is a way to overload the method name if `range` really is the best name for `color-range`.

Other than that. Thank you for a nice library - I enjoy it.

**Comment by dbox** [comment]
Hey @MortenHofft -

Thanks for letting us know.  Yes this is probably my fault. Didn't realize range was protected name. I'm assuming only fix is to rename it in axis. I will look into!

**Comment by jenius** [comment]
Same here, and thanks for the heads up. Anyone have thoughts on an alternate name? Maybe like `range-input`?

**Comment by dbox** [comment]
yeah that's what I was thinking

**Comment by dbox** [comment]
@jenius I can get this updated later. I seriously doubt that many people are using range yet.

Think it's fine to just put a note in the release and make it 0.5.3?

**Comment by jenius** [comment]
Haha definitely not. It's `0.6.0` for sure with that change, it's breaking. I'm sure there will be few issues as well, but it's only fair to be responsible!

**Comment by dbox** [comment]
cool

**Comment by dbox** [comment]
If axis was at 1.0 would we have had to make it 2.0?

**Comment by jenius** [comment]
Yes indeed!

**Comment by dbox** [comment]
Kinda hate that. In my mind 2.0 is all new. Ahh well. I'll update in a bit

**Comment by jenius** [comment]
Yeah I have agreed with this for most of my programming career. But honestly it's more important to me to know whether my shit will possibly break than to have clean shiny version numbers at this point. I've been screwed over by a number of packages that don't follow semver carefully, and it's just not worth it.

**Comment by dbox** [comment]
Yeah, totally. I get it. At least "semver in development" helps you curtail
it slightly.

**Comment by jenius** [comment]
Yeah, that's the theory. If you've done things right, releases should align that way anyway once you get to stable :grinning:

**Comment by dbox** [comment]
Unless you have a boneheaded contributor naming things incorrectly!

*puts on cone of shame*

**Comment by jenius** [comment]
Hahah I'm equally coned for not noticing. It happens though, not a big deal!

**Comment by dbox** [comment]
![slack-imgs-1 com](https://cloud.githubusercontent.com/assets/296130/13273631/86543cf8-da6a-11e5-9049-b82885f55b19.gif)

**Comment by jenius** [comment]
hahah amazing gif

**Comment by dbox** [comment]
@MortenHofft We've just pushed `0.6.0` which should hopefully fix your conflict. Let me know!

**Comment by MortenHofft** [comment]
Thank you. That was all very effective! To show my appreciation I just added another issue.
