### ISSUE TITLE
Style suggestion: Don't name mixins after HTML elements

### ISSUE THREAD

**Issue by zspecza** [jenius/axis#38]
I ran into this issue while adding baseline grid support:

![picture](https://a248.e.akamai.net/camo.github.com/156b6dccc82fc48d43643b682804dcad36507021/687474703a2f2f6779617a6f2e636f6d2f36393339306565376239643436663532666334313837303331313263383163622e706e67)

It took me a very long time to figure out what was causing it, roughly 2 hours or so. But I eventually found out what was wrong. I had these lines (roughly):

```
nav ul
nav ol
   some: property
```

It turns out that instead of setting `some: property`, it was actually calling your `nav()` mixin instead, and erroring out with a really confusing error message.

Changing it to this fixed the problem:

```
nav
  ul, ol
    some: property
```

And hence, I put forth this suggestion: don't name mixins after elements. It causes conflicts (that can be avoided as above, but not everyone will be as determined as I was to find out how to fix it, and they'll just complain)

So, instead of `nav()`, have it be `navbar()` or `navigation()` or something along those lines.

**Comment by dbartholomae** [comment]
Just noticed that `nav` is still used and even mentioned in the example. It would be great if it could get removed to avoid the error mentioned above! :)

**Comment by jenius** [comment]
For sure! Interested in submitting a PR to remove it? :grinning:

**Comment by dbox** [comment]
It would be breaking change. I'm not sure this is even a problem actually .
Were you able to reproduce error?

**Comment by dbartholomae** [comment]
Didn't encounter it myself yet, just seems to be an error that can be easily avoided and would be hard to catch otherwise.
But I do understand if continuity is more of a concern :)

**Comment by dbox** [comment]
I've just never encountered the naming actually being a problem, but I
don't use `nav` often.

**Comment by declandewet** [comment]
I can confirm that this is no longer an issue in Stylus - If memory serves me correctly, this behaviour was caused by a recursion bug in Stylus and was indirectly fixed by feature additions circa 2014. Those "best practices" are super duper outdated, mind you.

**Comment by dbartholomae** [comment]
Ok, thanks! :)
