### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by yoshuawuyts** [jenius/axis#58]
## [roots.cx/axis](roots.cx/axis)
- [ ] Jeets grid system with examples
- [ ] Add examples to vertical rhythm + rewording
- [ ] Add examples to utilities
- [ ] Reword confusing sections
- [ ] Improve [landing page](https://github.com/jenius/roots.cx). Fixes issues mentioned in https://github.com/jenius/roots.cx/issues/18#issuecomment-19724205
- [ ] How to remove surplus elements before deploying. Fixes https://github.com/jenius/axis/issues/47
## README.md
- [ ] Installation guide
- [ ] Quick overview of the capabilities
- [ ] Link to different elements
- [x] License
- [x] Travis build status badge
- [x] Contributors
- [ ] Browser compatibility badge
- [ ] Mention the #roots-dev channel on freenode

Time to add some suggestions.

**Comment by alejandroiglesias** [comment]
My vote for "Browser compatibility badge". I think it's important.

**Comment by jenius** [comment]
PR it in?
